# Generated by Django 5.2.8 on 2026-02-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_coupon_order_discount_amount'),
        ('orders', '0003_order_address_order_city_order_country_and_more'),
    ]

    operations = [
    ]
