# Generated by Django 5.2.8 on 2026-02-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_average_rating_product_review_count'),
        ('products', '0002_product_created_at'),
    ]

    operations = [
    ]
