"""Add image column to discussions

Revision ID: 84b4026b9e57
Revises: f2105d7b9fab
Create Date: 2025-11-08 18:38:22.180553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b4026b9e57'
down_revision = 'f2105d7b9fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussions', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
